-- MySQL Script generated by MySQL Workbench
-- 10/30/17 23:25:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `accountType` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_teachers_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_teachers_user`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacherId` INT NOT NULL,
  `className` VARCHAR(45) NULL,
  `discription` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`, `teacherId`),
  INDEX `fk_class_teacher_idx` (`teacherId` ASC),
  CONSTRAINT `fk_class_teacher`
    FOREIGN KEY (`teacherId`)
    REFERENCES `school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `classId` INT NULL DEFAULT NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_students_user_idx` (`userId` ASC),
  INDEX `fk_students_class1_idx` (`classId` ASC),
  CONSTRAINT `fk_students_user`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_students_class1`
    FOREIGN KEY (`classId`)
    REFERENCES `school`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `background` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usersId` INT NOT NULL,
  `subjectId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `background` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `usersId`, `subjectId`),
  INDEX `lessons_subjects_idx` (`subjectId` ASC),
  INDEX `lessons_users_idx` (`usersId` ASC),
  CONSTRAINT `lessons_subjects`
    FOREIGN KEY (`subjectId`)
    REFERENCES `school`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `lessons_users`
    FOREIGN KEY (`usersId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`apps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`apps` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subjectId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `background` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `subjectId`),
  INDEX `fk_apps_subjects1_idx` (`subjectId` ASC),
  CONSTRAINT `fk_apps_subjects1`
    FOREIGN KEY (`subjectId`)
    REFERENCES `school`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_admins_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_admins_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`parents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `studentId` INT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_parents_students_idx` (`studentId` ASC),
  CONSTRAINT `fk_parents_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_parents_students`
    FOREIGN KEY (`studentId`)
    REFERENCES `school`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`teacherSubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`teacherSubject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacherId` INT NOT NULL,
  `subjectId` INT NOT NULL,
  PRIMARY KEY (`id`, `subjectId`, `teacherId`),
  INDEX `fk_teacherSubject_teachers_idx` (`teacherId` ASC),
  INDEX `fk_teacherSubject_subjects_idx` (`subjectId` ASC),
  CONSTRAINT `fk_teacherSubject_teachers`
    FOREIGN KEY (`teacherId`)
    REFERENCES `school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teacherSubject_subjects`
    FOREIGN KEY (`subjectId`)
    REFERENCES `school`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`overlaps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`overlaps` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `accountType` VARCHAR(45) NULL,
  `default` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`menuitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`menuitems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `overlapId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `href` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `overlapId`),
  INDEX `dk_menuitems_overlaps_idx` (`overlapId` ASC),
  CONSTRAINT `dk_menuitems_overlaps`
    FOREIGN KEY (`overlapId`)
    REFERENCES `school`.`overlaps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `school`;

DELIMITER $$
USE `school`$$
CREATE TRIGGER `users_AFTER_INSERT` AFTER INSERT ON `users`
 FOR EACH ROW IF  (new.accountType="T") THEN
	
    INSERT INTO `teachers`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);

ELSEIF (new.accountType="A") THEN
  INSERT INTO `admins`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);
 
 ELSEIF (new.accountType="S") THEN
  INSERT INTO `students`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);
  
  ELSE
  INSERT INTO `parents`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);
  
END IF$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
