-- MySQL Script generated by MySQL Workbench
-- 01/04/18 01:59:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school` ;

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`users` ;

CREATE TABLE IF NOT EXISTS `school`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `accountType` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`teachers` ;

CREATE TABLE IF NOT EXISTS `school`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `background` MEDIUMTEXT NULL DEFAULT NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_teachers_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_teachers_user`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`class` ;

CREATE TABLE IF NOT EXISTS `school`.`class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacherId` INT NOT NULL,
  `className` VARCHAR(45) NULL,
  `discription` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`, `teacherId`),
  INDEX `fk_class_teacher_idx` (`teacherId` ASC),
  CONSTRAINT `fk_class_teacher`
    FOREIGN KEY (`teacherId`)
    REFERENCES `school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`students` ;

CREATE TABLE IF NOT EXISTS `school`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `classId` INT NULL DEFAULT NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_students_user_idx` (`userId` ASC),
  INDEX `fk_students_class1_idx` (`classId` ASC),
  CONSTRAINT `fk_students_user`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_students_class1`
    FOREIGN KEY (`classId`)
    REFERENCES `school`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`subjects` ;

CREATE TABLE IF NOT EXISTS `school`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `background` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`lessons` ;

CREATE TABLE IF NOT EXISTS `school`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` MEDIUMTEXT NULL,
  `background` MEDIUMTEXT NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `lessons_users_idx` (`userId` ASC),
  CONSTRAINT `lessons_users`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`apps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`apps` ;

CREATE TABLE IF NOT EXISTS `school`.`apps` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subjectId` INT NOT NULL,
  `name` MEDIUMTEXT NULL,
  `background` MEDIUMTEXT NULL,
  `url` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`, `subjectId`),
  INDEX `fk_apps_subjects1_idx` (`subjectId` ASC),
  CONSTRAINT `fk_apps_subjects`
    FOREIGN KEY (`subjectId`)
    REFERENCES `school`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`admins` ;

CREATE TABLE IF NOT EXISTS `school`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_admins_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_admins_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`parents` ;

CREATE TABLE IF NOT EXISTS `school`.`parents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `studentId` INT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_parents_students_idx` (`studentId` ASC),
  CONSTRAINT `fk_parents_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_parents_students`
    FOREIGN KEY (`studentId`)
    REFERENCES `school`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`teacherSubject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`teacherSubject` ;

CREATE TABLE IF NOT EXISTS `school`.`teacherSubject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacherId` INT NOT NULL,
  `subjectId` INT NOT NULL,
  PRIMARY KEY (`id`, `subjectId`, `teacherId`),
  INDEX `fk_teacherSubject_teachers_idx` (`teacherId` ASC),
  INDEX `fk_teacherSubject_subjects_idx` (`subjectId` ASC),
  CONSTRAINT `fk_teacherSubject_teachers`
    FOREIGN KEY (`teacherId`)
    REFERENCES `school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teacherSubject_subjects`
    FOREIGN KEY (`subjectId`)
    REFERENCES `school`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`overlaps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`overlaps` ;

CREATE TABLE IF NOT EXISTS `school`.`overlaps` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `accountType` VARCHAR(45) NULL,
  `default` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`menuitems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`menuitems` ;

CREATE TABLE IF NOT EXISTS `school`.`menuitems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `overlapId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `href` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`, `overlapId`),
  INDEX `dk_menuitems_overlaps_idx` (`overlapId` ASC),
  CONSTRAINT `dk_menuitems_overlaps`
    FOREIGN KEY (`overlapId`)
    REFERENCES `school`.`overlaps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `school`;

DELIMITER $$

USE `school`$$
DROP TRIGGER IF EXISTS `school`.`users_AFTER_INSERT` $$
USE `school`$$
CREATE TRIGGER `users_AFTER_INSERT` AFTER INSERT ON `users`
 FOR EACH ROW IF  (new.accountType="T") THEN
	
    INSERT INTO `teachers`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);

ELSEIF (new.accountType="A") THEN
  INSERT INTO `admins`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);
 
 ELSEIF (new.accountType="S") THEN
  INSERT INTO `students`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);
  
  ELSE
  INSERT INTO `parents`( `userId`, `name`, `lastName`, `active`) VALUES (new.id,'-','-',0);
  
END IF$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `school`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `school`;
INSERT INTO `school`.`users` (`id`, `login`, `password`, `email`, `accountType`) VALUES (1, 'uczen123', 'uczen123', 'uczen@u.pl', 'S');
INSERT INTO `school`.`users` (`id`, `login`, `password`, `email`, `accountType`) VALUES (2, 'nauczyciel123', 'nauczyciel123', 'nauczyciel@n.pl', 'T');
INSERT INTO `school`.`users` (`id`, `login`, `password`, `email`, `accountType`) VALUES (3, 'administrator123', 'administrator123', 'administrator@a.pl', 'A');
INSERT INTO `school`.`users` (`id`, `login`, `password`, `email`, `accountType`) VALUES (4, 'rodzic123', 'rodzic123', 'rodzic@r.pl', 'P');

COMMIT;


-- -----------------------------------------------------
-- Data for table `school`.`subjects`
-- -----------------------------------------------------
START TRANSACTION;
USE `school`;
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (1, 'J.polski', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (2, 'J.angielski', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (3, 'Historia', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (4, 'Matematyka', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (5, 'Fizyka', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (6, 'J.niemiecki', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (7, 'WOS', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (8, 'Chemia', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (9, 'Biologia', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (10, 'Geografia', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (11, 'Religia', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (12, 'Informatyka', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (13, 'W-F', NULL);
INSERT INTO `school`.`subjects` (`id`, `name`, `background`) VALUES (14, 'J.rosyjski', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `school`.`overlaps`
-- -----------------------------------------------------
START TRANSACTION;
USE `school`;
INSERT INTO `school`.`overlaps` (`id`, `name`, `accountType`, `default`) VALUES (1, 'Nauka', 'C', 0);
INSERT INTO `school`.`overlaps` (`id`, `name`, `accountType`, `default`) VALUES (2, 'Profil', 'C', 0);
INSERT INTO `school`.`overlaps` (`id`, `name`, `accountType`, `default`) VALUES (3, 'Dziennik', 'T', 1);
INSERT INTO `school`.`overlaps` (`id`, `name`, `accountType`, `default`) VALUES (4, 'Postępy', 'S', 1);
INSERT INTO `school`.`overlaps` (`id`, `name`, `accountType`, `default`) VALUES (5, 'Panel administracyjny', 'A', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `school`.`menuitems`
-- -----------------------------------------------------
START TRANSACTION;
USE `school`;
INSERT INTO `school`.`menuitems` (`id`, `overlapId`, `name`, `description`, `href`) VALUES (1, 1, 'Lekcje', NULL, '{\"action\":\"alllessons\"}');
INSERT INTO `school`.`menuitems` (`id`, `overlapId`, `name`, `description`, `href`) VALUES (2, 1, 'Zadania', NULL, NULL);
INSERT INTO `school`.`menuitems` (`id`, `overlapId`, `name`, `description`, `href`) VALUES (3, 1, 'Aplikacje', NULL, '{\"action\":\"subjectapp\"}');
INSERT INTO `school`.`menuitems` (`id`, `overlapId`, `name`, `description`, `href`) VALUES (4, 2, 'Mój profil', NULL, '{\"action\":\"profile\"}');
INSERT INTO `school`.`menuitems` (`id`, `overlapId`, `name`, `description`, `href`) VALUES (5, 2, 'Motywy', NULL, '{\"action\":\"theme\"}');
INSERT INTO `school`.`menuitems` (`id`, `overlapId`, `name`, `description`, `href`) VALUES (6, 2, 'Ustawienia', NULL, NULL);

COMMIT;

